sudo: required
services:
  - docker
language: node_js
node_js:
  - "node"
branches:
  only:
    - production
    - development
install:
  - npm install
after_success:
  - docker build -t $DOCKER_USERNAME/awix-$TRAVIS_BRANCH .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/awix-$TRAVIS_BRANCH
